// ... existing code ...
const HeroSection = styled.section`
    // ... existing code ...
    padding-top: 16px; // Reduced from a higher value
    // ... existing code ...
`;
// ... existing code ...