name: Deploy to Surge

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: |
          npm run build
          ls -la build/  # Debug: List build directory contents
          
      - name: Deploy to Surge
        run: |
          npm install -g surge
          ls -la  # Debug: List current directory
          ls -la build/  # Debug: Verify build directory
          surge ./build nicolette-portfolio.surge.sh --token ${{ secrets.SURGE_TOKEN }}
